### PR TITLE
11.1 log treatments

### PR DESCRIPTION
**Pull request by raeffu**

### CODE REVIEW

**Comment by sebastianhaeni** [comment]
You've got some things to do before this pull request can be merged:

* merge master into this branch
* add JavaDoc
* resolve TODOs
* use `getTreatments().remove(treatment)` instead of adding `removeTreatment(Treatment treatment)` to `Appointment`. => remove the clutter methods in `Appointment`
* use `HealVisConstants` for strings like "180px"

**Comment by raeffu** [comment]
@sebastianhaeni Below you see the adjustments i did according to your feedback.

* Master is already merged, did a rebase
* added JavaDoc
* TODO stays, can fix it in the end when we have time left (optional)
* removed clutter methods
* Using a constant for everything doesn't make sense.

**Comment by sebastianhaeni** [comment]
So far so good. 

Further feedback
* saving the treatments does not happen
* delete treatments is not implemented
* clear treatment name in input field after adding
* do not allow empty treatment
* if a date is invalid the treatment is still added but with empty time
* the treatment table is clipped when having too many items and is not usable anymore

**Comment by dave2sidefyn** [comment]
Constants makes absolutly sense in this case!
you will further have the possibilities to minimize contants and use all the same length in px. 

Maybe we should discuss that tonight!

**Comment by raeffu** [comment]
@sebastianhaeni 

* Didn't manage to save or delete anything over JPA, need to take a look at that together.
* added input validation etc.
* we can make the UI beautiful later, it's not so important. It works, you can scroll if table is clipped.
* added some more constants

* did merge new version of master (by rebasing), see [git graph](https://github.com/raeffu/ch.bfh.bti7081.s2015.Blue/network)

**Pull request merged**
